### ISSUE TITLE
wf-config is failing to build with stream 0.4.0

### ISSUE THREAD

**Issue by LastLightSith** [WayfireWM/wf-install#15]
Hi, I think Wayfire's 0.4.0 branch is pointing to old wf-config who's src/section.cpp don't include <stdexcept> and thats why I am getting  these errors while installing wayfire.
```

../subprojects/wf-config/src/section.cpp: In member function 'std::shared_ptr<wf::config::option_base_t> wf::config::section_t::get_option(const string&)':
../subprojects/wf-config/src/section.cpp:38:20: error: 'invalid_argument' is not a member of 'std'
   38 |         throw std::invalid_argument("Non-existing option " + name
      |                    ^~~~~~~~~~~~~~~~
../subprojects/wf-config/src/section.cpp: In member function 'void wf::config::section_t::register_new_option(std::shared_ptr<wf::config::option_base_t>)':
../subprojects/wf-config/src/section.cpp:60:20: error: 'invalid_argument' is not a member of 'std'
   60 |         throw std::invalid_argument(
      |                    ^~~~~~~~~~~~~~~~
```

here is full output:-
```
❯ ./install.sh --prefix /opt/debug_wayfire --system-wlroots --stream 0.4.0
Building Wayfire 0.4.0
Installation prefix: /opt/debug_wayfire
HEAD is now at 1c19515 update meson.build version to 0.4.0
HEAD is now at d865383 background: do not use deprecated std::random_shuffle
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `build'
[12/139] Compiling C++ object 'subprojects/wf-config/c6feab7@@wf-config@sha/src_section.cpp.o'
FAILED: subprojects/wf-config/c6feab7@@wf-config@sha/src_section.cpp.o 
c++ -Isubprojects/wf-config/c6feab7@@wf-config@sha -Isubprojects/wf-config -I../subprojects/wf-config -Isubprojects/wf-config/include -I../subprojects/wf-config/include -I/usr/include/libevdev-1.0/ -I/usr/include/libxml2 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -g -Wno-deprecated-declarations -fsanitize=address -g -fPIC -MD -MQ 'subprojects/wf-config/c6feab7@@wf-config@sha/src_section.cpp.o' -MF 'subprojects/wf-config/c6feab7@@wf-config@sha/src_section.cpp.o.d' -o 'subprojects/wf-config/c6feab7@@wf-config@sha/src_section.cpp.o' -c ../subprojects/wf-config/src/section.cpp
../subprojects/wf-config/src/section.cpp: In member function 'std::shared_ptr<wf::config::option_base_t> wf::config::section_t::get_option(const string&)':
../subprojects/wf-config/src/section.cpp:38:20: error: 'invalid_argument' is not a member of 'std'
   38 |         throw std::invalid_argument("Non-existing option " + name
      |                    ^~~~~~~~~~~~~~~~
../subprojects/wf-config/src/section.cpp: In member function 'void wf::config::section_t::register_new_option(std::shared_ptr<wf::config::option_base_t>)':
../subprojects/wf-config/src/section.cpp:60:20: error: 'invalid_argument' is not a member of 'std'
   60 |         throw std::invalid_argument(
      |                    ^~~~~~~~~~~~~~~~
[21/139] Compiling C++ object 'plugins/single_plugins/65acb7e@@move@sha/move.cpp.o'
ninja: build stopped: subcommand failed.

```

If i add manully add `#include <stdexcept>`to the wayfire/subprojects/wf-config/src/section.cpp, then it works

**Comment by ammen99** [comment]
Yeah, sorry, it has been fixed in master. We could probably add it to the 0.4 branch anyway.
